name: Wakatime Readme Stats
on:
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          COMMIT_BY_ME: True
          COMMIT_MESSAGE: "docs: update with dev metrics"
          COMMIT_USERNAME: princemuel
          COMMIT_EMAIL: vansomecsam@gmail.com

          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"

          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"

          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
